CREATE TABLE T_CLIENT_OAUTH (
  ID_CLIENT_OAUTH      NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  CLIENT_ID             VARCHAR2(100)  NOT NULL,
  CLIENT_SECRET_HASH    VARCHAR2(255)  NOT NULL,
  DESCRIZIONE           VARCHAR2(255),
  SCOPE_CONCESSI        VARCHAR2(500)  DEFAULT 'api.riderpay' NOT NULL,
  TOKEN_TTL_SECONDI     NUMBER         DEFAULT 3600 NOT NULL,
  FLAG_ATTIVO           CHAR(1)        DEFAULT 'S' NOT NULL CHECK (FLAG_ATTIVO IN ('S','N')),
  DT_CREAZIONE          TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  DT_ULTIMA_MODIFICA    TIMESTAMP,
  DT_ULTIMO_UTILIZZO    TIMESTAMP
);

CREATE UNIQUE INDEX UX_CLIENT_OAUTH_CLIENT_ID ON T_CLIENT_OAUTH (CLIENT_ID);
