ALTER TABLE T_BATCH_CARICAMENTO MODIFY ESITO VARCHAR2(20);

ALTER TABLE T_BATCH_CARICAMENTO DROP CONSTRAINT CK_BATCH_ESITO;

ALTER TABLE T_BATCH_CARICAMENTO ADD CONSTRAINT CK_BATCH_ESITO CHECK (
  ESITO IS NULL OR ESITO IN ('IN_CORSO','OK','KO','PARZIALE','ERRORE_TECNICO')
);
